import type { Client, Case, TimeEntry } from '../types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: 'Andersen & Partnere A/S',
    cvr: '12345678',
    contactPerson: 'Lars Andersen',
    contactEmail: 'lars@andersen.dk',
    contactPhone: '22334455',
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'c2',
    name: 'Byggeselskabet Norden ApS',
    cvr: '87654321',
    contactPerson: 'Mette Norden',
    contactEmail: 'mette@norden.dk',
    contactPhone: '33445566',
    createdAt: '2024-02-20T10:00:00Z',
  },
  {
    id: 'c3',
    name: 'TechVision Danmark',
    cvr: '11223344',
    contactPerson: 'Søren Tech',
    contactEmail: 'soren@techvision.dk',
    contactPhone: '44556677',
    createdAt: '2024-03-01T10:00:00Z',
  },
];

export const mockCases: Case[] = [
  {
    id: 'case1',
    clientId: 'c1',
    title: 'Hjemmeside redesign',
    description: 'Komplet redesign af virksomhedens hjemmeside med nyt CMS.',
    status: 'Aktiv',
    estimatedHours: 40,
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: 'case2',
    clientId: 'c1',
    title: 'SEO optimering Q1',
    description: 'Teknisk SEO og indholdsoptimering for Q1 2024.',
    status: 'Faktureret',
    estimatedHours: 20,
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'case3',
    clientId: 'c2',
    title: 'ERP-integration',
    description: 'Integration af eksisterende ERP-system med ny webshop.',
    status: 'Aktiv',
    estimatedHours: 80,
    createdAt: '2024-02-25T10:00:00Z',
  },
  {
    id: 'case4',
    clientId: 'c3',
    title: 'Support og vedligeholdelse',
    description: 'Løbende support og vedligehold af TechVisions platform.',
    status: 'Aktiv',
    estimatedHours: undefined,
    createdAt: '2024-03-05T10:00:00Z',
  },
];

export const mockEntries: TimeEntry[] = [
  {
    id: 'e1',
    caseId: 'case1',
    date: '2026-04-07',
    hours: 3,
    category: 'Grønne timer',
    description: 'Wireframes og designmøde',
    onSite: false,
    invoiced: false,
    createdAt: '2026-04-07T09:00:00Z',
  },
  {
    id: 'e2',
    caseId: 'case1',
    date: '2026-04-08',
    hours: 2.5,
    category: 'Grønne timer',
    description: 'Frontend implementering af header',
    onSite: false,
    invoiced: false,
    createdAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'e3',
    caseId: 'case4',
    date: '2026-04-07',
    hours: 1.5,
    category: 'Support',
    description: 'E-mail support og fejlretning',
    onSite: false,
    invoiced: false,
    createdAt: '2026-04-07T14:00:00Z',
  },
  {
    id: 'e4',
    caseId: 'case3',
    date: '2026-04-09',
    hours: 4,
    category: 'Grønne timer',
    description: 'API-integration med ERP',
    onSite: true,
    onSiteType: 'Installation',
    invoiced: false,
    createdAt: '2026-04-09T09:00:00Z',
  },
  {
    id: 'e5',
    caseId: 'case2',
    date: '2026-04-08',
    hours: 1,
    category: 'Salgsmøde',
    description: 'Opfølgningsmøde med Lars',
    onSite: true,
    onSiteType: 'Salgsmøde',
    invoiced: false,
    createdAt: '2026-04-08T13:00:00Z',
  },
  {
    id: 'e6',
    caseId: 'case4',
    date: '2026-04-10',
    hours: 2,
    category: 'Intern timer',
    description: 'Intern dokumentation og planlægning',
    onSite: false,
    invoiced: false,
    createdAt: '2026-04-10T09:00:00Z',
  },
];
